### ISSUE TITLE
enlever le copyright et mettre les mentions creative commons

### ISSUE THREAD

**Issue by mazerty** [lyonjug/lyonjug.org#44]

**Comment by clvi** [comment]
+1 pour ça.
Quelle version de Creative Commons tu penses utiliser ?

**Comment by mazerty** [comment]
je pensais mettre le même que celui que j'utilise : http://creativecommons.org/licenses/by-nc-sa/4.0

**Comment by mazerty** [comment]
ah mais en fait je l'ai déjà mis dans le fichier licence ^^
https://github.com/lyonjug/lyonjug.github.io/blob/master/LICENSE

**Comment by mazerty** [comment]
du coup il faut juste modifier le footer "copyright"

**Comment by claire-villard-sonarsource** [comment]
J'utilise CC BY-NC-SA aussi, donc ça me va ^^
